version: '3'

services:
    python:

        build: ./python
        ports:
            - 8000:80
        volumes:
            - ./python/workspace:/var/www/workspace
        # コンテナを起動したままにする
        tty: true
        container_name: docker-machine-learning-study
